"""Added answered_by column in phone_twilio_calls table

Revision ID: 01c0831aa734
Revises: cdfb8ef9b186
Create Date: 2025-08-18 12:39:15.740196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '01c0831aa734'
down_revision: Union[str, Sequence[str], None] = 'cdfb8ef9b186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_twilio_calls', sa.Column('answered_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_twilio_calls', 'answered_by')
    # ### end Alembic commands ###
