"""Added kind column in phone_twilio_calls table

Revision ID: 4fb0c27f2226
Revises: b1f0ec1a3030
Create Date: 2025-08-18 16:53:50.105249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4fb0c27f2226'
down_revision: Union[str, Sequence[str], None] = 'b1f0ec1a3030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        """migrations/versions/5c712f01f6dc_added_reason_field_to_phone_calls_table.py
        CREATE TYPE callkind AS ENUM (
            'api',
            'dial'
        );
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_twilio_calls', sa.Column('kind', sa.Enum('API', 'DIAL', name='callkind'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_twilio_calls', 'kind')
    # ### end Alembic commands ###
