"""Added reason field to phone_calls table

Revision ID: 5c712f01f6dc
Revises: 736e24cb4087
Create Date: 2025-08-18 12:11:18.248272

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "5c712f01f6dc"
down_revision: Union[str, Sequence[str], None] = "736e24cb4087"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE TYPE callreason AS ENUM (
            'answered-voicemail'
        );
        """
    )

    op.add_column(
        "phone_calls",
        sa.Column(
            "reason", sa.Enum("ANSWERED_VOICEMAIL", name="callreason"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("phone_calls", "reason")
    # ### end Alembic commands ###
