"""Added phone_calls and phone_twilio_calls table

Revision ID: 736e24cb4087
Revises: 
Create Date: 2025-08-17 12:45:39.550671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '736e24cb4087'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_call_sid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('to_phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_call_sid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_calls_from_call_sid'), 'phone_calls', ['from_call_sid'], unique=False)
    op.create_index(op.f('ix_phone_calls_to_call_sid'), 'phone_calls', ['to_call_sid'], unique=False)
    op.create_table('phone_twilio_calls',
    sa.Column('sid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['phone_calls.id'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_index(op.f('ix_phone_twilio_calls_call_id'), 'phone_twilio_calls', ['call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_twilio_calls_call_id'), table_name='phone_twilio_calls')
    op.drop_table('phone_twilio_calls')
    op.drop_index(op.f('ix_phone_calls_to_call_sid'), table_name='phone_calls')
    op.drop_index(op.f('ix_phone_calls_from_call_sid'), table_name='phone_calls')
    op.drop_table('phone_calls')
    # ### end Alembic commands ###
