"""Update case to CallStatus e CallReason enum

Revision ID: b1f0ec1a3030
Revises: 4a5ab5a93044
Create Date: 2025-08-18 12:55:36.355871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b1f0ec1a3030'
down_revision: Union[str, Sequence[str], None] = '4a5ab5a93044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
