"""Added Enum to status field in phone_calls table

Revision ID: cdfb8ef9b186
Revises: 5c712f01f6dc
Create Date: 2025-08-18 12:13:12.606216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cdfb8ef9b186'
down_revision: Union[str, Sequence[str], None] = '5c712f01f6dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
