"""Fix Enum coluns

Revision ID: f7112eb1212c
Revises: 4fb0c27f2226
Create Date: 2025-08-20 14:25:57.955180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f7112eb1212c'
down_revision: Union[str, Sequence[str], None] = '4fb0c27f2226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phone_calls', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('phone_twilio_calls', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('phone_twilio_calls', 'kind',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phone_twilio_calls', 'kind',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
    op.alter_column('phone_twilio_calls', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('phone_calls', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
